/* =====================================================================
   LES 10 ENQUÊTES
   hab : habitat utilisé pour le décor du chemin
   ===================================================================== */
const S=[
{k:'ail',edible:true,hab:'bois',name:'Ail des ours',latin:'Allium ursinum',pick:'Récolter',
 title:'Un tapis de grandes feuilles vertes',
 desc:'Bois frais de feuillus. Les feuilles couvrent le sol sur plusieurs mètres.',
 t:{odorat:'Forte odeur d\'ail, très nette au froissage.',
    loupe:'Chaque feuille possède son propre long pétiole distinct qui sort du sol.',
    coupe:'Tige souple, feuille fine et tendre.',
    habitat:'Sous-bois frais et ombragé de feuillus, sur sol riche, au printemps.'},
 ok:{t:'Juste',s:'Récolte validée',m:'C\'est du vrai Ail des ours.'},
 ko:{t:'Erreur mineure',s:'Occasion manquée',m:'L\'odeur d\'ail au froissage garantit la récolte en toute sécurité.'},
 why:'Odeur d\'ail au froissage + feuille portée par son propre pétiole : les deux critères ensemble signent l\'ail des ours.'},

{k:'colchique',edible:false,hab:'prairie',name:'Colchique d\'automne',latin:'Colchicum autumnale',pick:'Récolter',
 title:'De grandes feuilles vertes lancées au ras du sol',
 desc:'Prairie humide au printemps. Les feuilles ressemblent beaucoup aux précédentes.',
 t:{odorat:'Aucune odeur au froissage, odeur végétale neutre.',
    loupe:'Feuille rigide, sans pétiole, qui s\'enroule autour de la tige centrale.',
    coupe:'Tissu épais et gorgé d\'eau.',
    habitat:'Prairies et pâturages humides. Fleurit en automne, sans feuilles.'},
 ok:{t:'Juste',s:'Intoxication évitée',m:'Sans odeur d\'ail ni pétiole, c\'était un piège.'},
 ko:{t:'Erreur grave',s:'Mortel',m:'Colchique d\'automne ! Sa colchicine est mortelle dès 50 g de feuilles.'},
 why:'Feuille rigide engainante, sans pétiole et sans odeur : trois signaux qui excluent l\'ail des ours.'},

{k:'morille',edible:true,hab:'verger',name:'Morille commune',latin:'Morchella vulgaris',pick:'Récolter',
 title:'Un chapeau brun dressé, au relief marqué',
 desc:'Champignon printanier repéré au pied d\'un vieux pommier.',
 t:{loupe:'Chapeau creusé de véritables alvéoles ouvertes, séparées par des côtes saillantes.',
    coupe:'Entièrement creux, une seule cavité de la base du pied jusqu\'au sommet.',
    habitat:'Au sol sous des frênes et des pommiers sauvages, au printemps.',
    odorat:'Odeur douce et discrète de sous-bois humide.'},
 ok:{t:'Juste',s:'Récolte validée',m:'C\'est une authentique Morille commune. À ne jamais consommer crue : la cuisson est indispensable.'},
 ko:{t:'Erreur mineure',s:'Occasion manquée',m:'Les alvéoles et la cavité intérieure continue confirmaient la morille.'},
 why:'Alvéoles ouvertes bordées de côtes saillantes + cavité unique et continue à la coupe.'},

{k:'gyromitre',edible:false,hab:'conifere',name:'Gyromitre',latin:'Gyromitra esculenta',pick:'Récolter',
 title:'Un chapeau brun-roussâtre très plissé',
 desc:'Même saison, même allure générale que la précédente. Prudence.',
 t:{loupe:'Chapeau cérébriforme : des circonvolutions sinueuses, aucune alvéole ni côte saillante.',
    coupe:'Intérieur étagé, cloisonné en plusieurs petites cavités.',
    habitat:'Sols acides et sableux, souvent sous les conifères, au printemps.',
    odorat:'Odeur faible, un peu fruitée.'},
 ok:{t:'Juste',s:'Intoxication évitée',m:'Le relief en forme de cerveau interdit formellement la récolte.'},
 ko:{t:'Erreur grave',s:'Gravement toxique',m:'C\'est une Gyromitre ! Sa gyromitrine est gravement toxique, y compris par les vapeurs de cuisson.'},
 why:'Circonvolutions pleines en cerveau, jamais d\'alvéoles ouvertes, et intérieur cloisonné au lieu d\'une cavité unique.'},

{k:'gentiane',edible:true,hab:'alpage',name:'Gentiane jaune',latin:'Gentiana lutea',pick:'Récolter la racine',
 title:'Une grande plante aux tiges robustes',
 desc:'Pâturage d\'altitude. Vous cherchez la racine, utilisée en liquoristerie.',
 t:{loupe:'Feuilles opposées, insérées deux par deux l\'une en face de l\'autre.',
    coupe:'Tige nettement creuse.',
    habitat:'Sol acide des pâturages de montagne.',
    odorat:'Racine à l\'odeur forte et amère caractéristique.'},
 ok:{t:'Juste',s:'Récolte validée',m:'Bravo ! C\'est la Gentiane jaune.'},
 ko:{t:'Erreur mineure',s:'Occasion manquée',m:'Feuilles opposées et tige creuse : la signature absolue de la gentiane.'},
 why:'Feuilles opposées + tige creuse. La récolte de la racine est réglementée dans plusieurs départements.'},

{k:'veratre',edible:false,hab:'alpage',name:'Vératre blanc',latin:'Veratrum album',pick:'Récolter la racine',
 title:'Une grande plante dressée, sans ses fleurs',
 desc:'Même alpage, même silhouette. C\'est la confusion la plus meurtrière en montagne.',
 t:{loupe:'Feuilles alternes, insérées une à une à des hauteurs différentes.',
    coupe:'Tige totalement pleine et compacte.',
    habitat:'Alpages et mégaphorbiaies, souvent mêlé aux gentianes.',
    odorat:'Odeur végétale neutre, un peu âcre.'},
 ok:{t:'Juste',s:'Intoxication évitée',m:'Les feuilles alternes et la tige pleine signalaient le danger.'},
 ko:{t:'Erreur grave',s:'Mortel',m:'C\'est le Vératre blanc ! Ses alcaloïdes entraînent un choc cardiaque mortel.'},
 why:'Alternes et pleine contre opposées et creuse : deux critères opposés, vérifiables à coup sûr avant toute récolte.'},

{k:'tricholome',edible:true,hab:'lisiere',name:'Tricholome de la Saint-Georges',latin:'Calocybe gambosa',pick:'Récolter',
 title:'Un champignon blanc crème, assez massif',
 desc:'En lisière de forêt, poussant en ronds dans l\'herbe, au printemps.',
 t:{odorat:'Odeur très puissante et fraîche de farine fraîchement moulue.',
    loupe:'Lames très serrées, blanc à crème, échancrées près du pied.',
    coupe:'Chair ferme et blanche, sans changement de couleur.',
    habitat:'Lisières, prairies et haies, en cercles, autour du mois d\'avril.'},
 ok:{t:'Juste',s:'Récolte validée',m:'C\'est le Tricholome de la Saint-Georges, un excellent comestible de printemps.'},
 ko:{t:'Erreur mineure',s:'Occasion manquée',m:'L\'odeur puissante de farine fraîche est son critère déterminant.'},
 why:'Odeur de farine + lames serrées crème + chair immuable. Les entolomes toxiques ont des lames qui rosissent.'},

{k:'phalloide',edible:false,hab:'chenaie',name:'Amanite phalloïde',latin:'Amanita phalloides',pick:'Récolter',
 title:'Un chapeau vert-jaunâtre sous un chêne',
 desc:'La base du pied est enfouie sous les feuilles mortes. Dégagez-la avant de décider.',
 t:{loupe:'Un anneau sur le pied ET une volve en sac à la base, enfouie sous les feuilles.',
    coupe:'Chair fibreuse, pied se séparant nettement du chapeau.',
    odorat:'Odeur de rose fanée, douceâtre.',
    habitat:'Sous les chênes et les châtaigniers, de l\'été à l\'automne.'},
 ok:{t:'Juste',s:'Vie sauvée',m:'Dégager la base du pied pour repérer la volve en sac sauve des vies.'},
 ko:{t:'Erreur grave',s:'Mortel',m:'Amanite phalloïde ! Elle détruit de manière irréversible le foie, par cytolyse hépatique.'},
 why:'Anneau + volve en sac + lames blanches. L\'agaric, lui, a des lames roses puis brun chocolat et aucune volve.'},

{k:'coulemelle',edible:true,hab:'clairiere',name:'Grande lépiote, ou coulemelle',latin:'Macrolepiota procera',pick:'Récolter',
 title:'Un grand champignon dressé, au chapeau écailleux',
 desc:'Au bord d\'un chemin, en clairière. Il vous arrive au genou.',
 t:{loupe:'L\'anneau sur le pied coulisse librement, comme une bague.',
    coupe:'Pied creux, haut et fibreux.',
    habitat:'Clairières et bords de chemin, en fin d\'été et en automne.',
    odorat:'Odeur agréable de noisette.'},
 ok:{t:'Juste',s:'Récolte validée',m:'C\'est la Grande lépiote, un très bon comestible. On ne consomme que le chapeau.'},
 ko:{t:'Erreur mineure',s:'Occasion manquée',m:'L\'anneau mobile et le pied chiné creux validaient la cueillette.'},
 why:'Anneau coulissant + pied chiné et creux + grande taille. Les petites lépiotes, elles, sont mortelles : sous 10 cm, on s\'abstient.'},

{k:'arum',edible:false,hab:'jardin',name:'Baies d\'arum tacheté',latin:'Arum maculatum',pick:'Goûter',
 title:'Un épi compact de baies rouge vif, au sol',
 desc:'En bordure de jardin. Ces baies attirent surtout les enfants.',
 t:{loupe:'Grappe de baies serrées sur un épi nu, sans aucune feuille autour.',
    coupe:'Rempli d\'oxalate sous forme de micro-aiguilles, les raphides.',
    habitat:'Sous-bois et jardins accessibles, en fin d\'été.',
    odorat:'Aucune odeur attirante.'},
 ok:{t:'Juste',s:'Prudence parfaite',m:'Prudence parfaite face aux baies rouges d\'ornement !'},
 ko:{t:'Erreur grave',s:'Brûlure immédiate',m:'Baies d\'arum tacheté ! Le danger numéro un des enfants au jardin : brûlure buccale immédiate.'},
 why:'Règle d\'or au jardin : aucune baie rouge inconnue ne se goûte, et on montre la plante aux enfants pour qu\'ils l\'évitent.'}
];
const TOOLS=[['loupe','🔍','La loupe','Examen visuel'],['coupe','🔪','La coupe','Texture et structure'],
             ['odorat','👃','L\'odorat','Indice olfactif'],['habitat','🌿','L\'habitat','Contexte']];
